#!/usr/bin/env bash
# setup.sh — one-shot environment setup for ebpf-vthread-correlate.
#
# What it does (idempotent, safe to re-run):
#   1. Detects CPU arch and downloads the matching pre-built vthread-trace JDK
#      from the jdk21u GitHub release (no need to build OpenJDK yourself).
#   2. Verifies the download against its published SHA256.
#   3. Extracts it to a fixed location under this repo (.vthread-jdk/jdk).
#   4. Generates config/env.sh with JAVA_HOME / LIBJVM_PATH / JDK filled in,
#      so every script in this repo finds the JDK with zero manual editing.
#   5. Checks for the external tools the benchmarks need (bpftrace,
#      async-profiler, systemtap, maven) and reports what is missing.
#
# The pre-built JDK is OpenJDK 21u with -XX:+VThreadTraceProbes, built in an
# ubuntu:20.04 container (glibc 2.31) so it runs on any Linux with glibc >= 2.31.
#
# Usage:
#   ./setup.sh                 # download + verify + write config/env.sh
#   FORCE=1 ./setup.sh         # re-download even if JDK already present
set -euo pipefail

# ----- pin the release (single place to bump when you cut a new JDK) -----
GH_OWNER="Neltharion1127"
GH_REPO="jdk21u"
RELEASE_TAG="vthread-probes-v1"
# ------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$SCRIPT_DIR"
cd "$REPO_ROOT"

JDK_HOME_DIR="$REPO_ROOT/.vthread-jdk"     # download + extract live here
JDK_DIR="$JDK_HOME_DIR/jdk"                 # tarball extracts to top-level jdk/
ENV_FILE="$REPO_ROOT/config/env.sh"
FORCE="${FORCE:-0}"

say()  { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }
ok()   { printf '  \033[32m[OK]\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m[!!]\033[0m %s\n' "$*"; }
die()  { printf '\n\033[31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ---- 1. arch -> asset name ----
say "detect architecture"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  ASSET="jdk-vthread-x86_64.tar.gz" ;;
  aarch64) ASSET="jdk-vthread-aarch64.tar.gz" ;;
  *) die "unsupported architecture: $ARCH (expected x86_64 or aarch64)" ;;
esac
ok "arch = $ARCH  ->  asset = $ASSET"

BASE_URL="https://github.com/${GH_OWNER}/${GH_REPO}/releases/download/${RELEASE_TAG}"

# ---- 2. download + verify (skip if already extracted, unless FORCE) ----
if [ "$FORCE" != 1 ] && [ -x "$JDK_DIR/bin/java" ]; then
  ok "JDK already present at $JDK_DIR (use FORCE=1 to re-download)"
else
  say "download pre-built JDK ($RELEASE_TAG)"
  command -v wget >/dev/null 2>&1 || die "wget not found — install it (apt install wget)"
  mkdir -p "$JDK_HOME_DIR"
  cd "$JDK_HOME_DIR"

  wget -q --show-progress "${BASE_URL}/${ASSET}"        -O "$ASSET" \
    || die "download failed: ${BASE_URL}/${ASSET}"
  wget -q "${BASE_URL}/${ASSET}.sha256"                 -O "${ASSET}.sha256" \
    || die "sha256 download failed: ${BASE_URL}/${ASSET}.sha256"

  say "verify SHA256"
  # the .sha256 file is in standard `sha256sum` format ("hash  filename"),
  # so it can be fed to -c directly.
  sha256sum -c "${ASSET}.sha256" \
    || die "SHA256 mismatch — download corrupted or release was modified"
  ok "checksum verified"

  say "extract"
  rm -rf "$JDK_DIR"
  tar -xzf "$ASSET"
  [ -x "$JDK_DIR/bin/java" ] || die "extract failed: $JDK_DIR/bin/java not found"
  ok "extracted to $JDK_DIR"
  cd "$REPO_ROOT"
fi

# ---- 3. smoke-check the JDK actually runs + flag is present ----
say "verify JDK runs and exposes -XX:+VThreadTraceProbes"
if ! "$JDK_DIR/bin/java" -version >/dev/null 2>&1; then
  warn "java failed to run. Most likely a glibc mismatch."
  warn "this host: $(ldd --version 2>/dev/null | head -1)"
  die  "the pre-built JDK needs glibc >= 2.31"
fi
ok "java runs: $("$JDK_DIR/bin/java" -version 2>&1 | head -1)"

if "$JDK_DIR/bin/java" -XX:+VThreadTraceProbes -version >/dev/null 2>&1; then
  ok "-XX:+VThreadTraceProbes accepted"
else
  die "JDK does not recognise -XX:+VThreadTraceProbes — wrong build"
fi

# ---- 4. generate config/env.sh (the single source of truth) ----
say "write config/env.sh"
mkdir -p "$REPO_ROOT/config"
LIBJVM="$JDK_DIR/lib/server/libjvm.so"
[ -f "$LIBJVM" ] || die "libjvm.so not found at $LIBJVM"

cat > "$ENV_FILE" <<EOF
#!/usr/bin/env bash
# config/env.sh — GENERATED BY setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Single source of truth for JDK paths. Re-run ./setup.sh to regenerate.
# Source: ${GH_OWNER}/${GH_REPO} release ${RELEASE_TAG}, asset ${ASSET}

# Root of the vthread-trace JDK image.
export JAVA_HOME="$JDK_DIR"

# libjvm.so — bpftrace attaches USDT probes by this path.
export LIBJVM_PATH="$LIBJVM"

# Convenience alias used by run-usdt.sh / measure-oslevel.sh.
export JDK="$JDK_DIR"
EOF
ok "wrote $ENV_FILE"

# ---- 5. external toolchain check (informational; not auto-installed) ----
say "check external tools (install these yourself if missing)"
chk() {
  if command -v "$1" >/dev/null 2>&1; then
    ok "$1: $("$1" --version 2>&1 | head -1)"
  else
    warn "$1 missing — $2"
  fi
}
chk mvn       "maven, for building the benchmark jar (apt install maven)"
chk bpftrace  "apt install bpftrace / dnf install bpftrace (needs root to run)"
chk stap      "systemtap, apt install systemtap"

ASPROF="$REPO_ROOT/lib/libasyncProfiler.so"
if [ -f "$ASPROF" ]; then
  ok "async-profiler: $ASPROF"
else
  warn "async-profiler not found at lib/libasyncProfiler.so"
  warn "  download from https://github.com/async-profiler/async-profiler/releases"
  warn "  and place libasyncProfiler.so (matching your arch) at lib/"
fi

# ---- done ----
say "setup complete"
cat <<EOF
config/env.sh is ready. Scripts in this repo will now source it automatically.

Next steps:
  scripts/measure-oslevel.sh     # A/C/B smoke test — confirm the harness works
  scripts/profile-matrix.sh      # full benchmark matrix

If you are on bare-metal, also see the variance-control section in README.md
(CPU governor, turbo, taskset) before trusting absolute numbers.
EOF